-- MySQL Script generated by MySQL Workbench
-- ons 12 apr 2017 23:45:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fiberdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fiberdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fiberdb`;
USE `fiberdb` ;

-- -----------------------------------------------------
-- Table `fiberdb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiberdb`.`members` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `note` VARCHAR(100) NOT NULL,
  `from_year` DECIMAL NOT NULL,
  `to_year` DECIMAL NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `fiberdb`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contacts` (
  `member_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `preferred` TINYINT NOT NULL,
PRIMARY KEY (`member_id`),
  UNIQUE INDEX `contact_UNIQUE` (`member_id`, `value` ASC));


-- -----------------------------------------------------
-- Table `fiberdb`.`estates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estates` (
  `id` INT NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `note` VARCHAR(100) NOT NULL,
  `from_year` DECIMAL NOT NULL,
  `to_year` DECIMAL NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `estate_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `fiberdb`.`estate_dcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estate_dcs` (
  `date` DATE NOT NULL,
  `amount` DECIMAL NOT NULL,
  `tax` DECIMAL NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `months` INT NOT NULL,
  `estate_id` INT NOT NULL,
  PRIMARY KEY (`estate_id`, `months`, `year`, `type`),
  UNIQUE INDEX `estate_dcs_UNIQUE` (`estate_id`, `year`, `type`, `date` ASC));


-- -----------------------------------------------------
-- Table `fiberdb`.`configs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `configs` (
  `entered` DATETIME NOT NULL,
  `membership_fee` DECIMAL NOT NULL,
  `membership_tax` DECIMAL NOT NULL,
  `connection_fee` DECIMAL NOT NULL,
  `connection_tax` DECIMAL NOT NULL,
  `operator_fee` DECIMAL NOT NULL,
  `operator_tax` DECIMAL NOT NULL,
  `from_year` DECIMAL NOT NULL,
  PRIMARY KEY (`entered`),
  UNIQUE INDEX `configs_UNIQUE` (`entered` ASC));


-- -----------------------------------------------------
-- Table `fiberdb`.`member_dcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `member_dcs` (
  `date` DATE NOT NULL,
  `amount` DECIMAL NOT NULL,
  `tax` DECIMAL NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `member_id` INT NOT NULL,
  PRIMARY KEY (`member_id`, `type`, `year`),
  UNIQUE INDEX `member_dcs_UNIQUE` (`member_id`, `year`, `type`, `date` ASC));


-- -----------------------------------------------------
-- Table `fiberdb`.`members_estates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `members_estates` (
  `member_id` INT NOT NULL,
  `estate_id` INT NOT NULL,
  `from_year` DECIMAL NOT NULL,
  `to_year` DECIMAL NULL,
  PRIMARY KEY (`member_id`, `estate_id`),
  UNIQUE INDEX `members_estates_UNIQUE` (`member_id`, `estate_id` ASC));


-- -----------------------------------------------------
-- Table `fiberdb`.`estate_bi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estate_bi` (
  `estate_id` INT NOT NULL,
  `year` INT NOT NULL,
  `bi_months` INT NOT NULL,
  PRIMARY KEY (`year`, `estate_id`),
  UNIQUE INDEX `estate_bi_UNIQUE` (`estate_id`, `year` ASC));


-- -----------------------------------------------------
-- Table `fiberdb`.`estate_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estate_act` (
  `estate_id` INT NOT NULL,
  `year` INT NOT NULL,
  `act_months` INT NOT NULL,
  PRIMARY KEY (`year`, `estate_id`),
  UNIQUE INDEX `estate_act_UNIQUE` (`estate_id`, `year` ASC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
